name: Dica diária no WhatsApp

on:
  schedule:
    - cron: '0 11 * * 1-5'  # 08:00 horário de Brasília (UTC-3), dias úteis
  workflow_dispatch:

jobs:
  send-dica:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: pip install twilio

      - name: Executar script
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_WHATSAPP_FROM: ${{ secrets.TWILIO_WHATSAPP_FROM }}
          DESTINATION_NUMBER: ${{ secrets.DESTINATION_NUMBER }}
        run: python main.py
